### ISSUE TITLE
How support different screen size in android

### ISSUE THREAD

**Issue by Kirchhoff-** [Kirchhoff-/Android-Interview-Questions#359]

**Comment by 2tanayk** [comment]
Hey @Kirchhoff-  may I work on this issue?,I absolutely found your repo fantastic and would like to contribute 😄 ,so do let me know!

**Comment by Kirchhoff-** [comment]
Hi @2tanayk ! Yes of course you can deal with this issue, no problem) Thanks for your help!

**Comment by 2tanayk** [comment]
Thanks will soon work on it 😃
